# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Wqdo1TS8zbR06EjeIfQkA7HwtmOuBtx
"""

import numpy as np
import matplotlib.pyplot as plt

# X qiymatlari
x = np.linspace(0, 10, 100)
# Y qiymatlari
y = np.sin(x)

# Grafikni chizish
plt.plot(x, y, label="Sinus(x)", color="blue")

# Grafikning nomi va o'qlari
plt.title("Sinus Funktsiyasining Grafiki")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")

# To'rlarni qo'shish
plt.grid(True)

# Legenda qo'shish
plt.legend()

# Grafikni ko'rsatish
plt.show()

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)
x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)

plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', label='Nuqtalar')

plt.title('Tasodifiy Nuqtalar Scatter Grafiki', fontsize=14)
plt.xlabel('X qiymatlari', fontsize=12)
plt.ylabel('Y qiymatlari', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
pic1 = cv2.imread('./pics/hacker.jpg')
cv2_imshow(pic1)

pic1_wb = cv2.cvtColor(pic1, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic1_wb)

pic2 = cv2.imread('./pics/iccup.jpg')
cv2_imshow(pic2)

pic2_wb = cv2.cvtColor(pic2, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic2_wb)

pic3 = cv2.imread('./pics/sf.jpg')
cv2_imshow(pic3)

pic3_wb = cv2.cvtColor(pic3, cv2.COLOR_BGR2GRAY)
cv2_imshow(pic3_wb)